x-api: &api-base
  build:
    context: ./src
    dockerfile: Dockerfile
  networks:
    - app-network
  volumes:
    - sockets:/sockets
  restart: unless-stopped
  deploy:
    resources:
      limits:
        cpus: '0.40'
        memory: 165M

services:

  api1:
    <<: *api-base
    container_name: api1
    environment:
      SOCKET_PATH: /sockets/api1.sock
    cpuset: "0,1"
  api2:
    <<: *api-base
    container_name: api2
    environment:
      SOCKET_PATH: /sockets/api2.sock
    cpuset: "2,3"
  haproxy:
    image: haproxy:3.1-alpine
    user: root
    ports:
      - "9999:80"
    volumes:
      - ./infra/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    networks:
      - app-network
    restart: unless-stopped
    cpuset: "0,2"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 20M

networks:
  app-network:
    driver: bridge

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,mode=0777"
