x-api: &api-base
  image: ghcr.io/fagnerm/fmlab-rinha-fraude:latest
  user: root
  environment:
    ASPNETCORE_ENVIRONMENT: Production
  networks:
    - app-network
  volumes:
    - sock:/run/sock
  restart: unless-stopped
  deploy:
    resources:
      limits:
        cpus: '0.45'
        memory: 165M

services:

  api1:
    <<: *api-base
    container_name: api1
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      SOCKET_PATH: /run/sock/api1.sock
    cpuset: "0,1"

  api2:
    <<: *api-base
    container_name: api2
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      SOCKET_PATH: /run/sock/api2.sock
    cpuset: "2,3"

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sock:/run/sock
    depends_on:
      - api1
      - api2
    networks:
      - app-network
    restart: unless-stopped
    cpuset: "0,2"
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 20M

networks:
  app-network:
    driver: bridge

volumes:
  sock:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,mode=0777"
