<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Npgsql" Version="10.0.2" />
    <PackageVersion Include="Pgvector" Version="0.3.2" />
  </ItemGroup>
</Project>